import type { Patient, SystemActivityItem } from '../types';

export const MOCK_PATIENTS: Patient[] = [
  {
    id: 'PT-001',
    name: 'Arjun Sharma',
    avatar: 'AS',
    age: 45,
    gender: 'Male',
    bloodType: 'O+',
    condition: 'Hypertension',
    status: 'Stable',
    ward: 'Cardiology',
    doctor: 'Dr. Patel',
    phone: '+91 98765 43210',
    email: 'arjun.sharma@email.com',
    admittedDate: '2026-03-10',
    lastVisit: '2026-03-28',
    nextAppointment: 'Apr 5, 2026',
    vitals: { heartRate: 72, bloodPressure: '130/85', temperature: 98.4, oxygen: 97 },
    history: [
      { date: '2026-03-28', description: 'Follow-up: BP trending down on current regimen.' },
      { date: '2026-03-15', description: 'Admission vitals reviewed; cardiology consult cleared.' },
    ],
  },
  {
    id: 'PT-002',
    name: 'Priya Mehta',
    avatar: 'PM',
    age: 32,
    gender: 'Female',
    bloodType: 'A+',
    condition: 'Diabetic Ketoacidosis',
    status: 'Critical',
    ward: 'ICU',
    doctor: 'Dr. Rao',
    phone: '+91 99887 76655',
    email: 'priya.mehta@email.com',
    admittedDate: '2026-03-25',
    lastVisit: '2026-03-30',
    nextAppointment: 'Apr 1, 2026',
    vitals: { heartRate: 110, bloodPressure: '88/60', temperature: 101.2, oxygen: 91 },
  },
  {
    id: 'PT-003',
    name: 'Rohan Verma',
    avatar: 'RV',
    age: 60,
    gender: 'Male',
    bloodType: 'B-',
    condition: 'Post-Op Hip Replacement',
    status: 'Recovering',
    ward: 'Orthopaedics',
    doctor: 'Dr. Singh',
    phone: '+91 97654 32109',
    email: 'rohan.verma@email.com',
    admittedDate: '2026-03-18',
    lastVisit: '2026-03-29',
    nextAppointment: 'Apr 8, 2026',
    vitals: { heartRate: 78, bloodPressure: '125/80', temperature: 99.1, oxygen: 96 },
  },
  {
    id: 'PT-004',
    name: 'Sunita Kapoor',
    avatar: 'SK',
    age: 55,
    gender: 'Female',
    bloodType: 'AB+',
    condition: 'Chronic Kidney Disease',
    status: 'Stable',
    ward: 'Nephrology',
    doctor: 'Dr. Gupta',
    phone: '+91 91234 56789',
    email: 'sunita.kapoor@email.com',
    admittedDate: '2026-03-05',
    lastVisit: '2026-03-27',
    nextAppointment: 'Apr 3, 2026',
    vitals: { heartRate: 68, bloodPressure: '140/90', temperature: 98.6, oxygen: 98 },
  },
  {
    id: 'PT-005',
    name: 'Vikram Nair',
    avatar: 'VN',
    age: 28,
    gender: 'Male',
    bloodType: 'O-',
    condition: 'Appendicitis',
    status: 'Recovering',
    ward: 'Surgery',
    doctor: 'Dr. Joshi',
    phone: '+91 98765 12345',
    email: 'vikram.nair@email.com',
    admittedDate: '2026-03-22',
    lastVisit: '2026-03-30',
    nextAppointment: 'Apr 6, 2026',
    vitals: { heartRate: 82, bloodPressure: '118/75', temperature: 99.8, oxygen: 97 },
  },
  {
    id: 'PT-006',
    name: 'Ananya Das',
    avatar: 'AD',
    age: 41,
    gender: 'Female',
    bloodType: 'A-',
    condition: 'Pneumonia',
    status: 'Critical',
    ward: 'Pulmonology',
    doctor: 'Dr. Kumar',
    phone: '+91 99001 23456',
    email: 'ananya.das@email.com',
    admittedDate: '2026-03-27',
    lastVisit: '2026-03-31',
    nextAppointment: 'Apr 2, 2026',
    vitals: { heartRate: 98, bloodPressure: '95/65', temperature: 102.5, oxygen: 88 },
  },
  {
    id: 'PT-007',
    name: 'Deepak Pillai',
    avatar: 'DP',
    age: 70,
    gender: 'Male',
    bloodType: 'B+',
    condition: 'Coronary Artery Disease',
    status: 'Stable',
    ward: 'Cardiology',
    doctor: 'Dr. Patel',
    phone: '+91 96543 21098',
    email: 'deepak.pillai@email.com',
    admittedDate: '2026-03-12',
    lastVisit: '2026-03-26',
    nextAppointment: 'Apr 10, 2026',
    vitals: { heartRate: 65, bloodPressure: '135/82', temperature: 98.2, oxygen: 96 },
  },
  {
    id: 'PT-008',
    name: 'Kavya Reddy',
    avatar: 'KR',
    age: 26,
    gender: 'Female',
    bloodType: 'O+',
    condition: 'Migraine',
    status: 'Discharged',
    ward: 'Neurology',
    doctor: 'Dr. Mehta',
    phone: '+91 98234 56712',
    email: 'kavya.reddy@email.com',
    admittedDate: '2026-03-20',
    lastVisit: '2026-03-25',
    nextAppointment: 'Apr 15, 2026',
    vitals: { heartRate: 74, bloodPressure: '112/72', temperature: 98.6, oxygen: 99 },
  },
  {
    id: 'PT-009',
    name: 'Manish Tiwari',
    avatar: 'MT',
    age: 50,
    gender: 'Male',
    bloodType: 'AB-',
    condition: 'Liver Cirrhosis',
    status: 'Critical',
    ward: 'Gastroenterology',
    doctor: 'Dr. Shah',
    phone: '+91 97890 12456',
    email: 'manish.tiwari@email.com',
    admittedDate: '2026-03-28',
    lastVisit: '2026-03-31',
    nextAppointment: 'Apr 1, 2026',
    vitals: { heartRate: 104, bloodPressure: '90/58', temperature: 100.9, oxygen: 92 },
  },
  {
    id: 'PT-010',
    name: 'Shruti Bose',
    avatar: 'SB',
    age: 38,
    gender: 'Female',
    bloodType: 'A+',
    condition: 'Rheumatoid Arthritis',
    status: 'Stable',
    ward: 'Rheumatology',
    doctor: 'Dr. Agarwal',
    phone: '+91 91122 33456',
    email: 'shruti.bose@email.com',
    admittedDate: '2026-03-08',
    lastVisit: '2026-03-24',
    nextAppointment: 'Apr 7, 2026',
    vitals: { heartRate: 70, bloodPressure: '122/78', temperature: 98.8, oxygen: 98 },
  },
  {
    id: 'PT-011',
    name: 'Karan Malhotra',
    avatar: 'KM',
    age: 35,
    gender: 'Male',
    bloodType: 'O+',
    condition: 'Fractured Femur',
    status: 'Recovering',
    ward: 'Orthopaedics',
    doctor: 'Dr. Singh',
    phone: '+91 98001 22334',
    email: 'karan.malhotra@email.com',
    admittedDate: '2026-03-16',
    lastVisit: '2026-03-30',
    nextAppointment: 'Apr 4, 2026',
    vitals: { heartRate: 80, bloodPressure: '120/76', temperature: 98.9, oxygen: 97 },
  },
  {
    id: 'PT-012',
    name: 'Neha Jain',
    avatar: 'NJ',
    age: 29,
    gender: 'Female',
    bloodType: 'B+',
    condition: 'Hyperthyroidism',
    status: 'Stable',
    ward: 'Endocrinology',
    doctor: 'Dr. Pandey',
    phone: '+91 99321 54678',
    email: 'neha.jain@email.com',
    admittedDate: '2026-03-14',
    lastVisit: '2026-03-28',
    nextAppointment: 'Apr 9, 2026',
    vitals: { heartRate: 88, bloodPressure: '116/74', temperature: 98.3, oxygen: 99 },
  },
];

/** Volume dynamics — spline chart series */
export const CHART_DATA = [
  { name: 'Oct', admissions: 38, discharges: 32, critical: 5 },
  { name: 'Nov', admissions: 42, discharges: 38, critical: 7 },
  { name: 'Dec', admissions: 55, discharges: 50, critical: 9 },
  { name: 'Jan', admissions: 48, discharges: 44, critical: 6 },
  { name: 'Feb', admissions: 62, discharges: 55, critical: 8 },
  { name: 'Mar', admissions: 70, discharges: 63, critical: 11 },
];

export const WARD_DATA = [
  { name: 'Cardiology', occupancy: 18, capacity: 24 },
  { name: 'ICU', occupancy: 11, capacity: 12 },
  { name: 'Orthopaedics', occupancy: 14, capacity: 18 },
  { name: 'Neurology', occupancy: 12, capacity: 15 },
  { name: 'Surgery', occupancy: 17, capacity: 20 },
  { name: 'Nephrology', occupancy: 7, capacity: 9 },
  { name: 'Pulmonology', occupancy: 9, capacity: 11 },
];

export const SYSTEM_ACTIVITY: SystemActivityItem[] = [
  { title: 'Patient admission: Unit 4B — Case #8291', time: '14:22:18 GMT' },
  { title: 'Vitals alert: Bed 12 — SpO₂ threshold', time: '14:18:02 GMT', urgent: true },
  { title: 'Shift rotation: Night team acknowledged', time: '13:55:41 GMT' },
  { title: 'Lab batch released: Chemistry panel', time: '13:40:09 GMT' },
  { title: 'Discharge planning: PT-008 cleared', time: '12:08:33 GMT' },
];
